# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

##
# @file GUI.py
# @author Matus Tvarozny

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(311, 271)
        Form.setMinimumSize(QtCore.QSize(311, 271))
        Form.setMaximumSize(QtCore.QSize(311, 271))
        Form.setStyleSheet("\n"
"background-color: rgb(60, 60, 60);")
        self.pushButton_point = QtWidgets.QPushButton(Form)
        self.pushButton_point.setGeometry(QtCore.QRect(10, 220, 41, 41))
        self.pushButton_point.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_one = QtWidgets.QPushButton(Form)
        self.pushButton_one.setGeometry(QtCore.QRect(10, 170, 41, 41))
        self.pushButton_one.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_one.setObjectName("pushButton_one")
        self.pushButton_eight = QtWidgets.QPushButton(Form)
        self.pushButton_eight.setGeometry(QtCore.QRect(60, 70, 41, 41))
        self.pushButton_eight.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.pushButton_five = QtWidgets.QPushButton(Form)
        self.pushButton_five.setGeometry(QtCore.QRect(60, 120, 41, 41))
        self.pushButton_five.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_five.setObjectName("pushButton_five")
        self.pushButton_two = QtWidgets.QPushButton(Form)
        self.pushButton_two.setGeometry(QtCore.QRect(60, 170, 41, 41))
        self.pushButton_two.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_two.setObjectName("pushButton_two")
        self.pushButton_zero = QtWidgets.QPushButton(Form)
        self.pushButton_zero.setGeometry(QtCore.QRect(60, 220, 41, 41))
        self.pushButton_zero.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.pushButton_seven = QtWidgets.QPushButton(Form)
        self.pushButton_seven.setGeometry(QtCore.QRect(10, 70, 41, 41))
        self.pushButton_seven.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.pushButton_four = QtWidgets.QPushButton(Form)
        self.pushButton_four.setGeometry(QtCore.QRect(10, 120, 41, 41))
        self.pushButton_four.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_four.setObjectName("pushButton_four")
        self.pushButton_nine = QtWidgets.QPushButton(Form)
        self.pushButton_nine.setGeometry(QtCore.QRect(110, 70, 41, 41))
        self.pushButton_nine.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.pushButton_six = QtWidgets.QPushButton(Form)
        self.pushButton_six.setGeometry(QtCore.QRect(110, 120, 41, 41))
        self.pushButton_six.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_six.setObjectName("pushButton_six")
        self.pushButton_three = QtWidgets.QPushButton(Form)
        self.pushButton_three.setGeometry(QtCore.QRect(110, 170, 41, 41))
        self.pushButton_three.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(169, 169, 169);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_three.setObjectName("pushButton_three")
        self.pushButton_rightbracket = QtWidgets.QPushButton(Form)
        self.pushButton_rightbracket.setGeometry(QtCore.QRect(210, 70, 41, 41))
        self.pushButton_rightbracket.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_rightbracket.setObjectName("pushButton_rightbracket")
        self.pushButton_ABS = QtWidgets.QPushButton(Form)
        self.pushButton_ABS.setGeometry(QtCore.QRect(110, 220, 41, 41))
        self.pushButton_ABS.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_ABS.setObjectName("pushButton_ABS")
        self.pushButton_mul = QtWidgets.QPushButton(Form)
        self.pushButton_mul.setGeometry(QtCore.QRect(160, 120, 41, 41))
        self.pushButton_mul.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_plus = QtWidgets.QPushButton(Form)
        self.pushButton_plus.setGeometry(QtCore.QRect(160, 170, 41, 41))
        self.pushButton_plus.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_squareroot = QtWidgets.QPushButton(Form)
        self.pushButton_squareroot.setGeometry(QtCore.QRect(160, 220, 41, 41))
        self.pushButton_squareroot.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_squareroot.setObjectName("pushButton_squareroot")
        self.pushButton_fact = QtWidgets.QPushButton(Form)
        self.pushButton_fact.setGeometry(QtCore.QRect(260, 170, 41, 41))
        self.pushButton_fact.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_fact.setObjectName("pushButton_fact")
        self.pushButton_div = QtWidgets.QPushButton(Form)
        self.pushButton_div.setGeometry(QtCore.QRect(210, 120, 41, 41))
        self.pushButton_div.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_minus = QtWidgets.QPushButton(Form)
        self.pushButton_minus.setGeometry(QtCore.QRect(210, 170, 41, 41))
        self.pushButton_minus.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_power = QtWidgets.QPushButton(Form)
        self.pushButton_power.setGeometry(QtCore.QRect(210, 220, 41, 41))
        self.pushButton_power.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_power.setObjectName("pushButton_power")
        self.pushButton_equal = QtWidgets.QPushButton(Form)
        self.pushButton_equal.setGeometry(QtCore.QRect(260, 220, 41, 41))
        self.pushButton_equal.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_DEL = QtWidgets.QPushButton(Form)
        self.pushButton_DEL.setGeometry(QtCore.QRect(260, 120, 41, 41))
        self.pushButton_DEL.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_DEL.setObjectName("pushButton_DEL")
        self.pushButton_AC = QtWidgets.QPushButton(Form)
        self.pushButton_AC.setGeometry(QtCore.QRect(260, 70, 41, 41))
        self.pushButton_AC.setStyleSheet("background-color: rgb(255, 103, 0);\n"
"font: 75 11pt \"Arial\";\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_AC.setObjectName("pushButton_AC")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 291, 51))
        self.lineEdit.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(245, 245, 245);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_leftbracket = QtWidgets.QPushButton(Form)
        self.pushButton_leftbracket.setGeometry(QtCore.QRect(160, 70, 41, 41))
        self.pushButton_leftbracket.setStyleSheet("font: 75 11pt \"Arial\";\n"
"background-color: rgb(238, 238, 238);\n"
"border-style: outset;\n"
"border-radius: 8px;")
        self.pushButton_leftbracket.setObjectName("pushButton_leftbracket")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyCalculator"))
        self.pushButton_point.setText(_translate("Form", "."))
        self.pushButton_one.setText(_translate("Form", "1"))
        self.pushButton_eight.setText(_translate("Form", "8"))
        self.pushButton_five.setText(_translate("Form", "5"))
        self.pushButton_two.setText(_translate("Form", "2"))
        self.pushButton_zero.setText(_translate("Form", "0"))
        self.pushButton_seven.setText(_translate("Form", "7"))
        self.pushButton_four.setText(_translate("Form", "4"))
        self.pushButton_nine.setText(_translate("Form", "9"))
        self.pushButton_six.setText(_translate("Form", "6"))
        self.pushButton_three.setText(_translate("Form", "3"))
        self.pushButton_rightbracket.setText(_translate("Form", ")"))
        self.pushButton_ABS.setText(_translate("Form", "ABS"))
        self.pushButton_mul.setText(_translate("Form", "×"))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_squareroot.setText(_translate("Form", "√"))
        self.pushButton_fact.setText(_translate("Form", "!"))
        self.pushButton_div.setText(_translate("Form", "÷"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_power.setText(_translate("Form", "^"))
        self.pushButton_equal.setText(_translate("Form", "="))
        self.pushButton_DEL.setText(_translate("Form", "DEL"))
        self.pushButton_AC.setText(_translate("Form", "AC"))
        self.pushButton_leftbracket.setText(_translate("Form", "("))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
